name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          
      - name: Sync dependencies
        run: uv sync
        
      - name: Generate language stats SVG
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: uv run python main.py
        
      - name: Verify SVG was generated
        run: test -f languages.svg
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Update language stats SVG"
          file_pattern: "languages.svg"